version: '3.7'

services:
  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sequelize
    ports:
      - '5432:5432'